### ISSUE TITLE
Mention datas synchronisation in README

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-mobile#104]
Command to launch if Geotrek-rando V1 is used.
Other if Geotrek-randoo V2 is used ?

**Comment by SBats** [comment]
It's not the same app version depending on your API version. We need to clean branches but data synchronisation doesn't depend on a command.
I'll add informations about versions compatibility.

**Comment by camillemonchicourt** [comment]
Yes I used the wrong word. I meant generation, not synchronisation. In case of using Geotrek-rando (and mobile) V1.

Thanks.

**Comment by SBats** [comment]
Mm ok ! About generation it's depending on where come from your data, not the app itself. If you are using full Geotrek suite, it's handle on Geotrek Admin. You should ask on the admin repo to document it.

**Comment by camillemonchicourt** [comment]
Yes, that's why I had in mind. It would be useful to mention how Geotrek-mobile gets datas. What you mentioned with "informations about versions compatibility". As it is partially clear for me. 
Something like...

Geotrek-mobile gets datas from Geotrek-rando or Geotrek-admin depending on the version used. At each launch of the application, it connects to the API of Geotrek-rando ou Geotrek-admin to verify if datas changed and download datas if necessary (GeoJSON, images and tiles). 
- If you are using Geotrek-mobile V1, you need to plug it to a V1 of Geotrek-rando. Your Geotrek-mobile will get datas from the Geotrek-rando. These datas have to be generated regulary by Geotrek-rando V1 (see Geotrek-rando documentation).
- If you are using Geotrek-mobile V2... ???

Thanks.

**Comment by SBats** [comment]
Ok, I understand. I'll add informations about this in the readme yes.

**Comment by camillemonchicourt** [comment]
:+1:
