### ISSUE TITLE
Add touristic contents and events to trek detail

### ISSUE THREAD

**Issue by gutard** [makinacorpus/Geotrek-mobile#110]

**Comment by camillemonchicourt** [comment]
- Being able to configure which categories to include in settings.
- Have to discuss if POIs, touristic events and contents are displayed all together in the same list by distance (or name if no GPS on device) or if they are grouped by category.

**Comment by camillemonchicourt** [comment]
OK, donc on valide que les contenus et événements touristiques ne sont accessibles que depuis les fiches RANDOS.
Les résultats ne sont pas mélangés avec les PATRIMOINES.
Les contenus touristiques sont regroupés par catégories (Hébergements, Restaurants, Animations...)
Dans chaque bloc, les éléments sont triés comme les POI (par distance GPS si localisation dispo ou sinon par ordre alphabétique). 
Les contenus des fiches CONTENUS TOURISTIQUES pouvant être importants, on affiche un résumé et une fiche complète au clic sur celle-ci. 

Reste une question sur le mode d'affichage : 
- Les blocs les uns en dessous des autres
- Des onglets
- Un accordéon

Le système des onglets nous parait le plus adapté car il évite de tout dérouler pour accéder au contenu choisi.

**CARTE :**

Ces différentes catégories de contenus pourront être affichés sur la carte de l'itinéraire et il sera aussi possible de les masquer, tout comme les PATRIMOINES. 

**GENERAL :**

On est bien conscient que cela va alourdir le contenu de l'appli mais on n'intégrera pas toutes les catégories de contenus touristiques et il est crucial d'embarquer au moins les infos sur les hébergements en plus des patrimoines, quand on est sur de l'itinérance. 

A voir aussi si les performances suivent.

**Comment by SBats** [comment]
According to what you say, that's a lot of decisions to make and refactoring. We need to decide first what we are doing whit it and then only we'll be able to separate it in multiple smaller tasks.

**Comment by SBats** [comment]
I close this ticket and remove it from the sprint as it has been divided in smaller ones durint our meeting with @camillemonchicourt .
