### ISSUE TITLE
RESET FILTERS button - STYLE

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-mobile#114]
On Android, it looks very similar to filters. 
May would be easier to read if it had another colour ?
And maybe it should be a bit higher.

**Comment by SBats** [comment]
I add your other comment about this button in order not to forget anything


Would be good to add a small margin at bottom.

**Comment by camillemonchicourt** [comment]
OK, I just checked in the IOS version and the styles are not like in Android application.
In IOS all list are white and RESET button is black. This is better as we see clarly that it is another tool and no confusion with advanced filters.
In Android, lists and reset buttons have black background.
