### ISSUE TITLE
Put trek-detail parts in collapsable containers

### ISSUE THREAD

**Issue by SBats** [makinacorpus/Geotrek-mobile#116]

**Comment by camillemonchicourt** [comment]
Only in the second part of the detail page, POIs, touristic contents.
Or you had in mind to also put the trek info in the collapsable container too ?

**Comment by SBats** [comment]
I was thinking about everything that has a blue title, meaning :
- Description (the bloc under the slideshow of pictures)
- Elevation
- Transports
- Advices
- Infrastructure
- Information desks
- Children treks
- Parents treks
- POIs
- Touristics contents

**Comment by camillemonchicourt** [comment]
It would make a lot of collapsed parts with very short contents. 
We think that it is better to have one collapsed container for POIs and one for TOURISTIC CONTENTS.

**Comment by SBats** [comment]
And so we keep everything else always visible ?
Can't we at least collapse children and parents ?

**Comment by camillemonchicourt** [comment]
Yes because these are general trek informations. 
Good point about ITINERANCY. OK to collapse children (étapes) and parents (séjour).

**Comment by SBats** [comment]
Ok
