### ISSUE TITLE
Add markers display panel on detail map

### ISSUE THREAD

**Issue by SBats** [makinacorpus/Geotrek-mobile#118]
Add a button and an associated panel to allow user to chose which types of markers he want by default.

It should be a checkbox system allowing multiple selections.
By default, "patrimoines" part is selected

**Comment by SBats** [comment]
About the icon used for the button on the map.
I've tried what we talked about but I think it's really hard to rad on a small screen. I've also tried a simpler option, but still it's not perfect.

![toggle-marker-v1](https://cloud.githubusercontent.com/assets/3982958/10490677/9a6f540a-72a2-11e5-9123-43fb7a897ca1.png)

![toggle-marker-v2](https://cloud.githubusercontent.com/assets/3982958/10490703/b977936c-72a2-11e5-8b6f-b0cdea897a4d.png)


Otherwise I've tried with a much simpler icon which is just the pin icon. After a talk with our ergonom we think it's enough to understand.

![screenshot-0 0 0 0 9000 2015-10-14 18-29-18](https://cloud.githubusercontent.com/assets/3982958/10490685/a441082a-72a2-11e5-9026-88109dd8c529.png)


What do you think ?

**Comment by camillemonchicourt** [comment]
Yes indeed, good for me
