### ISSUE TITLE
Add touristics contents part to trek detail

### ISSUE THREAD

**Issue by SBats** [makinacorpus/Geotrek-mobile#121]
Depends on https://github.com/makinacorpus/Geotrek/issues/1515

**Comment by SBats** [comment]
How do you want the part to be called on the detail page ? @camillemonchicourt 
Ideally if you have the en, fr, and it translations :)

**Comment by camillemonchicourt** [comment]
Services would be the best Word.
Same in FR and UK
Servizio in IT

**Comment by SBats** [comment]
Mm isn't it redundant with the real services like drinking points, repairing persons, etc ... ?

**Comment by camillemonchicourt** [comment]
Yes it is actually as what it actually called SERVICES are not services at all but are trek_infos and should change name. https://github.com/makinacorpus/Geotrek/issues/1475

**Comment by SBats** [comment]
Ok
