### ISSUE TITLE
Handling svg marker icons coloration

### ISSUE THREAD

**Issue by SBats** [makinacorpus/Geotrek-mobile#124]
We don't have any way to handle properly markers coloration on the mobile app for the moment. @fredericbonifas suggested that the admin should be able to send a colored version of a simple svg icon, which is smart. 
The other option I see is handling it the same way as rando (downloading the markup of the icon and use it directly inside a divIcon) but I realy fear for speed impacts on mobile.
Another solution is to repaint in js the svg each time we add the layer, but because of the markers display menu functionnality it will be overconsupming on the cpu. (a lot of call multiple times by use)

**Comment by camillemonchicourt** [comment]
Yes, maybe the best for RANDO and MOBILE, would be to have a field color in touristic content categories.
And order ?

**Comment by camillemonchicourt** [comment]
Or original uploaded SVG can't have a colour rather than all be black ?

**Comment by SBats** [comment]
1 - The problem is not getting the color but applying it to the icon.
2 - It's black because it has no color. The idea is that we can have the same svg across multiple platforms and style it by changing its color.

The thing is, you have 2 options to style svg content :
- put it in an object tag and style it via javasript (but it's heavy on resources, especially for large collections)
- inline the svg markup where you need it which allow you to style it in css.

The second option is used in RANDO.

Another issue I see with having it already colored in the admin is that you can't use the smae icon on different colors (ex: use it in color on white background, then in white on colored background)

**Comment by camillemonchicourt** [comment]
OK i understand

**Comment by camillemonchicourt** [comment]
OK so the actual solution is to upload SVG icons in white in Geotrek-admin and to display them like this on a black marker in Geotrek-mobile. 
Having them in white is also a good point for Geotrek-rando.
