### ISSUE TITLE
Improve collapsables style

### ISSUE THREAD

**Issue by SBats** [makinacorpus/Geotrek-mobile#125]
@camillemonchicourt . What would you prefer for them ? make them higher or another color ? Or both .?

**Comment by camillemonchicourt** [comment]
I fear that having another colour would not look very good. 
Some ideas : 
Maybe just having a black (or dark grey) border ?
Or don't use the app colour (purple in our case) to fill the container but for the text and arrow and border ?

**Comment by SBats** [comment]
I agree about another color. It would be too much.
Here what I would look like with the border and text colored only :
![screenshot-0 0 0 0 9000 2015-10-26 14-10-13](https://cloud.githubusercontent.com/assets/3982958/10729676/5a37c500-7beb-11e5-8257-55ec39239243.png)

**Comment by camillemonchicourt** [comment]
OK let's try that !

**Comment by camillemonchicourt** [comment]
In your screenshot the arrow change of direction when opened. But not in the app. Normal ?

**Comment by SBats** [comment]
Mm strange it does change on my phone. Which device are you testing on ?

**Comment by camillemonchicourt** [comment]
LG G2, Android 4.4.2
Just tried on a Nexus 7, Android 5.1.1 and it worked.

**Comment by SBats** [comment]
Then it's an issue with the transform css property on old Android phones. You can open another ticket for this if you want but I think it's not really important. (better for modern but not a problem for older versions)
