### ISSUE TITLE
V2 - Accessibility filter

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-mobile#133]
It is not displayed in filters. Normal ?

**Comment by SBats** [comment]
There's currently no accessibility filter.

**Comment by camillemonchicourt** [comment]
Yes, they have been added in Geotrek V2 when USAGES was removed and splitted into PRATIQUES and ACCESSIBLITIES but were not included into Geotrek-mobile V2.

**Comment by SBats** [comment]
Yes
