### ISSUE TITLE
Rename USAGES as PRATICES in trek detail page

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-mobile#135]

**Comment by SBats** [comment]
Can you provide us all the translations also please ?

**Comment by camillemonchicourt** [comment]
FR : Pratique
EN : Practice
IT : Pratiche

As ``nav_trek_map.use`` in https://github.com/makinacorpus/Geotrek-mobile/pull/134

In this (/app/scripts/globalization/locales.js) file I also just noticed that in EN 'nav_trek_map.use': 'Uses' should be modified to 'nav_trek_map.use': 'Practices',

**Comment by SBats** [comment]
Ok thx
