### ISSUE TITLE
V2.1 - Map tiles are displayed in Android images gallery

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-mobile#138]

**Comment by camillemonchicourt** [comment]
Je confirme sur mon telephone (LG G2 - Android 4.4) que j'ai toutes les tuiles et toutes les photos de l'appli GTE mobile test qui se sont mises dans la galerie. Quand je regarde le détail d'une image, son chemin est ``/storage/emulated/0/rando-ecrins-v2/media`` ou ```/storage/emulated/0/rando-ecrins-v2/tiles``.
Je n'avais pas ça avec Rando Ecrins (Geotrek-mobile 1.1.0), ni Rando Loire Atlantique ni Rando Mercantour qui sont en 2.0.0.

Pour être vraiment sur, j'ai désinstallé l'appli (d'ailleurs ça n'a pas supprimé les fichiers, j'ai du supprimer à la main le dossier /rando-ecrins-V2 avec tous les contenus - https://github.com/makinacorpus/Geotrek-mobile/issues/140), je l'ai réinstallée, l'ai lancé. Puis je suis allé dans la galerie et là... Rien dans la galerie... 
Ce n'est qu'après avoir redémarré le téléphone que les images et les tuiles sont apparues dans la galerie.

**Comment by SBats** [comment]
I've found the cause of this... there was a typo on the line for persistent location in the config.xml. My bad !

**Comment by camillemonchicourt** [comment]
OK, cool it is fixed.
