### ISSUE TITLE
2.1 - Downloading datas each time

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-mobile#139]
ON 2.1, each time I launch the app I get the message "Données mises à jour, les données concernant les randonnées ont été mises à jour. Si vous avez...". And when I click on OK, I appears another time. 
I close the app, relaunch it, I get the message again. 
It appears twice and each time. Behind the message, it loading treks and maps each time too.

**Comment by SBats** [comment]
On which version of the app are you experiencing this ? If it's the one we've sent you it's normal as it's linked directly to a test admin. It doesn't work as when it's a synced version on a prod server.

**Comment by camillemonchicourt** [comment]
OK that's the reason !
