### ISSUE TITLE
Rename "Transport public"

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-mobile#142]
Le terme "Transport public" pose problème dans certains cas où les transports en commun sont assurés par des opérateurs privés. 

Dans Geotrek-admin, ce champs est intitulé "Transports en commun". Donc pour régler le problème, utiliser ce même intitulé partout. 

Transports avec un S.

EN : Il semblerait que même si ils sont privés, il n'y a que le terme "Public transports"
IT : Idem en italien où il faut rester sur "trasporti pubblici".

Moralité : Y a que les français qui sont pénibles ! :-)

**Comment by SBats** [comment]
Closed by https://github.com/makinacorpus/Geotrek-mobile/pull/147
