### ISSUE TITLE
Advice(s), singular or plurial ?

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-mobile#143]
Some noticed that they can be several advices on 1 trek.
So the best would be to label this field "Advice(s)".
Dont look very good I think so let's go fro "Advices". 

"Recommandations" in French
"Raccomendazioni" in Italian

**Comment by SBats** [comment]
Closed by https://github.com/makinacorpus/Geotrek-mobile/pull/149
