### ISSUE TITLE
V2 app can't work if the touristic contents are disabled or not synced on admin side

### ISSUE THREAD

**Issue by SBats** [makinacorpus/Geotrek-mobile#145]
Actually the app always try to load touristic contents and events, which end un in 404 errors and routing issues if the admin doesn't have them synced or active.

We should add a setting to allow the app to ignore touristic contents and, ideally, to inform the user if the files are required but not present.

**Comment by camillemonchicourt** [comment]
Oh OK. Indeed we actually dont have touristic content in database for GTE-mobile.
As it is controlled by Geotrek-admin synchronisation (https://github.com/makinacorpus/Geotrek/blob/master/docs/synchronization.rst#synchronization-filtered-by-touristic-content-categories), I thought that it was enough for Geotrek-mobile to know if there is some touristic content and which categories are synchronized with Geotrek-mobile.

I dont really understand the need for a setting.

**Comment by SBats** [comment]
A setting would prevent geotrek mobile from doing useless requests and it could allows us to handle real files issues independently.

**Comment by camillemonchicourt** [comment]
OK I see.

**Comment by camillemonchicourt** [comment]
An easier solution wouldnt it be to always include some empty touristic content geojson in the API ?
Maybe it dont make sense ?

**Comment by SBats** [comment]
I really think it's better to have at the same time an option in the mobile to prevent useless requests and another fix to allow the app to have a functional routing when there's a 404 on json resources.

**Comment by BastienAlvez** [comment]
https://github.com/makinacorpus/Geotrek-mobile/pull/148
 Add one boolean setting TOURISTIC to ignore touristic content

**Comment by camillemonchicourt** [comment]
:+1:
