### ISSUE TITLE
V2 - PNG icons dont work in filters

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-mobile#169]
I get this for practices in Geotrek-mobile (GTE). Because our icons are PNG ?

![screenshot_2015-12-18-17-18-46_resized](https://cloud.githubusercontent.com/assets/4418840/11901394/a39dd7d6-a5ab-11e5-8d77-8787ba8598db.png)

**Comment by SBats** [comment]
Yes indeed. This menu was not conceived to contain png icons. We have a system for img type checking on rando, but not on mobile.

**Comment by camillemonchicourt** [comment]
I planned to change for SVG icons in any case.

**Comment by camillemonchicourt** [comment]
Icons are now SVG
