### ISSUE TITLE
Advice - Add S to Recommandation like in V1X

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-mobile#180]

**Comment by SBats** [comment]
Mm could you provide details on this one ? The translation is already with a s in my locales files.

**Comment by camillemonchicourt** [comment]
OK good then.
I saw the commit in V1.X but not in master and it has no S in our actual GTE apk so it was just a reminder.

**Comment by SBats** [comment]
It was fixed in 364551015a9c0c6e1162c2b19ee8f1025d24c778
