### ISSUE TITLE
Static pages - Cible WEB and HIDDEN displayed in Mobile

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-mobile#182]
Just tried to create a static page with Cible = Web. 
It is displayed in Rando but also in Mobile.

**Comment by camillemonchicourt** [comment]
Just tried to create a HIDDEN static page and this one is also displayed in Geotrek-mobile.

**Comment by SBats** [comment]
There's indeed an issue in the condition. It still tests the old value for target and should be updated.
