### ISSUE TITLE
Map - POI modale - No image displayed when the trek is downloaded

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-mobile#186]
While the POI images are displayed in the trek detail page, when we clic on a POI from the map, it displays the message used when the mobile dont receive datas. 
"Veuillez vous connecter pour afficher cette image"

**Comment by SBats** [comment]
Fixed by f7c1487bf2f8209e6a2f9a14947ff0631b77fd0f
