### ISSUE TITLE
Rename TOUR as SEJOUR

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-mobile#81]
Pour l'itinérance, utiliser plutot le terme SEJOUR pour les fiches parents que TOUR.

**Comment by camillemonchicourt** [comment]
Pas sur en fait... Séjour ça colle pas vraiment mais Tour non plus. 
On reboucle...

**Comment by camillemonchicourt** [comment]
OK donc après réflexion, on pense que le plus adapté est le terme Itinérance pour les fiches mères. 

Tour est trop connoté grande boucle. Le terme itinéraire aurait pu convenir mais il s'applique aussi à la randonnée à la journée.

On fera pareil dans Geotrek-rando donc.

**Comment by camillemonchicourt** [comment]
Pour l'anglais on a demandé à notre agende de traduction. 
Pour la moment dans Geotrek-admin on parle de ITINERANCY mais on avait un doute, voila leur réponse : 

"Multi-day hiking" et 'Multi-day hikes’. 

Le premier c'est le nom de l'activité, donc il devrait convenir pour la plupart des contextes.

Voici un exemple d'un site néo-zélandais à ce sujet : http://www.newzealand.com/int/multi-day-hikes/ mais il en existe beaucoup d’autres.

On pourrait aussi dire 'long-distance hiking'.

Ça fait un peu plus lourd du coup mais certainement plus précis et adapté. On va trancher ça ! :-)

**Comment by SBats** [comment]
The thing is, hiking is associated with walking activity. It doesn't match if the trek is a horse riding activity or a bicycle one.

**Comment by camillemonchicourt** [comment]
Good point !

**Comment by SBats** [comment]
Have you decided about this point ?

**Comment by camillemonchicourt** [comment]
OK so some English people confirmed to me that ITINERANCY isnt correct.
It looks like the best solution in English would be "Multi-day trekking".
In Italian it would be "Escursionismo itinerante".
In French "Itinérance".
