### ISSUE TITLE
Download trek / confirmation message

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-mobile#85]
Le message actuel est : "Vous allez télécharger la carte détaillée de ce itinéraire. Etes-vous sûr ?"
Il devrait plutôt être : 
"Vous allez télécharger la carte détaillée et les images de cet itinéraire. Etes-vous sûr ?"

**Comment by SBats** [comment]
fixed by 73ad6b58620a7951910fb235a2dc63521e74a5ce
