### ISSUE TITLE
Bloc TRANSPORT PUBLIC affiché même si vide

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-mobile#87]
![screenshot_2015-06-17-10-47-44](https://cloud.githubusercontent.com/assets/4418840/8202959/b53f25b6-14de-11e5-880b-e7a350e7328d.png)

**Comment by SBats** [comment]
fixed by bb70fd1e35e67beb0e45b554a301ebccbb438133
