### ISSUE TITLE
Problème d'affichage du chapeau

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-mobile#88]
L’arrière-plan du bloc TITRE, COMMUNE, DEPART "déborde" parfois sur le chapeau. 

![screenshot_2015-06-16-13-11-50](https://cloud.githubusercontent.com/assets/4418840/8202996/f2b7e630-14de-11e5-9a06-ab34787527fd.png)

**Comment by camillemonchicourt** [comment]
Je n'arrivais pas à trouver à quel moment cela se produisait.
Je pense avoir trouvé.
Quand on affiche une fiche rando, c'est OK.
On affiche la carte puis de nouveau la fiche et c'est là que le chapeau change de style et que l’arrière-plan se superpose.

**Comment by camillemonchicourt** [comment]
Superposition sur ANDROID.
Sur IOS, le texte devient gris.

**Comment by SBats** [comment]
fixed by 1b353aca0904e8776dc33ea6d10b61941b3b5ab3

**Comment by camillemonchicourt** [comment]
It looks like it still happen in V2 as I just saw the same problem on PnMercantour mobile app, just released and based on Geotrek-mobile V2.
The SUMMARY style is not the same when you display a trek detail page for the first time, then go on map. When you go back on the trek details, the SUMMARY style is different.

**Comment by camillemonchicourt** [comment]
I also think that in V2 there should be 2 blocks of information more separated as it is in our V1 app : 

- 1 with trek title, cities and departures 
- the other with Summary and Ambiance

Or at least have different styles such as bold for Summary and italic for Ambiance.
