### ISSUE TITLE
New trek published don't appear in APP

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-mobile#89]
- Je lance l'appli.
- Je la ferme totalement. 
- Je publie une nouvelle rando sur Geotrek. C'est une rando de test qui avait été publiée en février puis dépubliée une fois les tests réalisés.
- Je relance la génération des fichiers mobiles depuis Geotrek-rando (``bin/python ./manage.py build_mobile_data http://rando.ecrins-parcnational.fr``).
- Je relance l'appli. 
- Il relance bien le téléchargement des données et m'avertit que des données ont été modifiées. 
- Cependant le nouvel itinéraire n'est pas disponible dans l'appli. Il n'y a toujours que 101 randos dans l'appli alors que 102 sont publiées.

**Comment by camillemonchicourt** [comment]
Comme indiqué précédemment, cette rando-test avait initialement été publiée en février puis dépubliée le jour-même une fois les tests réalisés. Son ID est ``926351``.
Là je l'ai republié puis relancé la génération des données mobiles mais elle n'est pas ajoutée à l'appli mobile comme précisé ci-dessus.
Sur le serveur de notre Geotrek-rando, on retrouve bien un fichier ``trek-926351.zip`` dans ``/home/xxxx/rando-ecrins/var/input/fr/api/trek`` mais il date de février 2015.
Par contre il n'est pas présent dans le fichier ``trek.geojson`` du dossier ``/home/xxxx/rando-ecrins/var/input/fr/api/trek/trek.zip``.
On retrouve aussi un fichier ``trek-926351.zip`` dans ``/home/xxxx/rando-ecrins/var/input/tiles`` mais il date aussi de février 2015.

**Comment by camillemonchicourt** [comment]
J'ai essayé de modifier le texte de cette rando pour voir si ça permettrait de la charger mais toujours pas. 
J'en déduis donc que les fichiers mobiles ont été générés en février quand on l'a publié la première fois. 
Puis que la rando a été supprimée de ``trek.geojson`` quand on l'a dépubliée en février. 
Et qu'aujourd'hui, si on la republie, cela n'est pas pris en compte. 
Les tuiles ``trek-926351.zip`` ne sont pas regénérées quand je lance ``bin/python ./manage.py build_mobile_data http://rando.ecrins-parcnational.fr`` (alors qu'il les regénère pour toutes les autres randos) ni les fichiers associés dans ``/home/xxxx/rando-ecrins/var/input/fr/api/trek``

**Comment by camillemonchicourt** [comment]
Ahhhh autant pour moi. 
J'avais oublié un détail important....
La génération des fichiers mobiles se fait sur les données présentes côté Geotrek-rando... Et non Geotrek-admin... Or je publiais la rando de test puis lançais le BUILD_MOBILE_DATA sans avoir lancé la synchro du portail avant cela...
Désolé pour le dérangement.... :-)

**Comment by leplatrem** [comment]
ça pourrait être une bonne idée de question à ajouter à la section "troubleshooting" :)

**Comment by camillemonchicourt** [comment]
:+1:
