### ISSUE TITLE
TITLE ERROR on launch on S5, Android 4.4.4

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-mobile#90]
Feedback from an user of Rando Ecrins mobile 1.0.0 (beta) :

USER : The android app gives an error when you start it on a Samsung.

PNE : Can you try again ?
What is the error message ? 
Which model is your phone and which Android version is it ?
Thanks for your feedback.

USER : The error says TITLE ERROR.
I have an S5 with android 4.1

USER : The phone has Android 4.4.4. Not 4.1

**Comment by camillemonchicourt** [comment]
OK I think I found the problem. 
This user has his phone in a language not supported by the app (not French, nor Italian nor English). 

Just tried to set my mobile in Deutsch and reinstall the app and got the same problem. 

When launching it, I get this error : 

```
    error_title
    error_message
    OK
```

**Comment by SBats** [comment]
Thx for the feedback. In fact we just had the same issue on CG44 version. We've chose that if the device language is not in the available one, we fallback on default language in settings.

**Comment by camillemonchicourt** [comment]
Great, perfect choice !
