### ISSUE TITLE
BACK button goes to previous page, not to list

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-mobile#92]
Je suis sur une fiche RANDO, j'affiche sa carte puis de nouveau sa fiche.
En cliquant sur le bouton de RETOUR tout en haut de la page, cela me ramène à la page précédente (carte de la rando) et non à la liste des RANDOS.

**Comment by SBats** [comment]
This is intended. We return to the calling page of the modal. It's not always the list. It can be the map or another step of a tour ...

**Comment by camillemonchicourt** [comment]
It is not the good way. 
We go on a trek detail page, we check the map and then go back on detail. 
When we click on BACK, we want to go on TREKS LIST, not on TREK MAP, as we just went on it and can clic on MAP button if we want to check MAP again...

This BACK button, should have only one action = GO BACK TO TREKS LIST.

**Comment by SBats** [comment]
I disagrea. Example :
- you come from the main map with all treks and you show detail page. Back is expected to send back to map, not list

**Comment by camillemonchicourt** [comment]
Not false. :-)
Didnt thought to this case. 

Anyway the main case when you use it is when you check a trek detail page, go on map then go back on trek details and then want to check another trek. 
So going back to PREVIOUS page is maybe not the perfect way. 

But I understand with you case that just having one ACTION that would go back on list is not the good way. 

We keep it for later. :-)
