### ISSUE TITLE
Missing field in English version / Distance

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-mobile#96]
Just tried to install the app with my mobile settings in English. 
It seems to work well as it only load the 38 treks that we published in this language. 

But on trek detail pages, the DISTANCE (below LENGTH) symbol and data isnt displayed.

**Comment by SBats** [comment]
I don't have this bug.Is it still true for you ? If so can you provide more details please ?

**Comment by camillemonchicourt** [comment]
OK so I just uninstalled my French RANDO ECRINS app. 
I put my phone in English in Phone settings.
I downloaded RANDO ECRINS again and launched it. 
So this time it was in English and with English content (only 38 treks) and the problem didnt happened again...

Dont know what happened previous time, maybe I was tired...
