### ISSUE TITLE
FLATPAGES_TARGETS don't work in Geotrek-mobile

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-mobile#97]
On Geotrek-rando 1.X, it was explained in README that it is possible to select where FLATPAGES are displayed (https://github.com/makinacorpus/Geotrek-rando/blob/v1.X/README.rst)

>
You can hide the static pages from the navigation bar, but setting a specific target. They be will reachable at /page/<slug> but won't be listed in the navigation. By default only ``all`` and ``rando`` are shown in the navigation bar. In Geotrek-mobile, only targets ``all`` and ``mobile`` will be taken into account.

> Example : 
FLATPAGES_TARGETS = {
'avertissements': 'mobile', 'credits': 'hidden'
}

I had a page to hide on Geotrek-rando and one to hide on Geotrek-mobile, so my settings in ``prod.py`` are : 

```
FLATPAGES_TARGETS = {
	'votre-avis': 'rando',
	'mentions-legales-mobile': 'mobile'
}
```

It worked well on Geotrek-rando as the page ``mentions-legales-mobile`` is not displayed on our Geotrek-rando but it don' work on Geotrek-mobile as ``votre-avis`` is also displayed in our Geotrek-mobile.

**Comment by SBats** [comment]
Fixed by 5922a3889d60cfb7988c704a9e8f43e18546f4f0
