### ISSUE TITLE
IOS - BACK button on trek detail pages

### ISSUE THREAD

**Issue by camillemonchicourt** [makinacorpus/Geotrek-mobile#99]
In French version, it says CANCEL.
It should say at least BACK and would be better in FRENCH.
If we went on trek maps before, same problem as explained here - https://github.com/makinacorpus/Geotrek-mobile/issues/92

**Comment by SBats** [comment]
Fixed with 60c24cc4bdcbd0c024cd131cc28f6ac141f7f4ca
